// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKidQwx74FPHy_yPv-0MRjJO9uxqetGJc',
    appId: '1:794037180140:web:5426c69d9f3900efdcf7c9',
    messagingSenderId: '794037180140',
    projectId: 'project-gta-44e31',
    authDomain: 'project-gta-44e31.firebaseapp.com',
    storageBucket: 'project-gta-44e31.firebasestorage.app',
    measurementId: 'G-TQW24F2RNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC43N9M0m9ZQ3T-M3mZIK968NC34suEC1E',
    appId: '1:794037180140:android:ff650ef113b58244dcf7c9',
    messagingSenderId: '794037180140',
    projectId: 'project-gta-44e31',
    storageBucket: 'project-gta-44e31.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbb4ad1lM7XL1RCxdnp0-PFy2Nt-6lBQU',
    appId: '1:794037180140:ios:3ac29ac10d247793dcf7c9',
    messagingSenderId: '794037180140',
    projectId: 'project-gta-44e31',
    storageBucket: 'project-gta-44e31.firebasestorage.app',
    androidClientId: '794037180140-1p77urkrglvr2bthu9tthfgo6vbepqvf.apps.googleusercontent.com',
    iosClientId: '794037180140-de5313h13m6el5e1o1rbi06ao5nkoa8e.apps.googleusercontent.com',
    iosBundleId: 'com.softinvo.globaltextileaxis',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbb4ad1lM7XL1RCxdnp0-PFy2Nt-6lBQU',
    appId: '1:794037180140:ios:eec1379fbe7e9056dcf7c9',
    messagingSenderId: '794037180140',
    projectId: 'project-gta-44e31',
    storageBucket: 'project-gta-44e31.firebasestorage.app',
    androidClientId: '794037180140-1p77urkrglvr2bthu9tthfgo6vbepqvf.apps.googleusercontent.com',
    iosClientId: '794037180140-d8f975m6dr7vgirq6v14it9dlpr8oad2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKidQwx74FPHy_yPv-0MRjJO9uxqetGJc',
    appId: '1:794037180140:web:5426c69d9f3900efdcf7c9',
    messagingSenderId: '794037180140',
    projectId: 'project-gta-44e31',
    authDomain: 'project-gta-44e31.firebaseapp.com',
    storageBucket: 'project-gta-44e31.firebasestorage.app',
    measurementId: 'G-TQW24F2RNB',
  );
}
