// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC43N9M0m9ZQ3T-M3mZIK968NC34suEC1E',
    appId: '1:794037180140:web:xxxxxx', // Placeholder - Web App ID not in JSON
    messagingSenderId: '794037180140',
    projectId: 'project-gta-44e31',
    authDomain: 'project-gta-44e31.firebaseapp.com',
    storageBucket: 'project-gta-44e31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC43N9M0m9ZQ3T-M3mZIK968NC34suEC1E',
    appId: '1:794037180140:android:d6e9813447300cd6dcf7c9',
    messagingSenderId: '794037180140',
    projectId: 'project-gta-44e31',
    storageBucket: 'project-gta-44e31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC43N9M0m9ZQ3T-M3mZIK968NC34suEC1E',
    appId: '1:794037180140:ios:xxxxxx', // Placeholder - iOS App ID not in JSON
    messagingSenderId: '794037180140',
    projectId: 'project-gta-44e31',
    storageBucket: 'project-gta-44e31.firebasestorage.app',
    iosBundleId: 'com.gta.app',
  );
}
